name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build interpret example
      uses: crazy-max/ghaction-xgo@v1.1.0
      with:
          xgo_version: latest
          go_version: 1.14.x
          dest: build/interpret
          pkg: ./cmd/interpret/
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          x: false
          ldflags: -s -w
      
    - name: Build handles example
      uses: crazy-max/ghaction-xgo@v1.1.0
      with:
          xgo_version: latest
          go_version: 1.14.x
          dest: build/handles
          pkg: ./cmd/handles/
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          x: false
          ldflags: -s -w

    - name: Build wrengo
      uses: crazy-max/ghaction-xgo@v1.1.0
      with:
          xgo_version: latest
          go_version: 1.14.x
          dest: build/handles
          pkg: ./cmd/wrengo/
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          x: false
          ldflags: -s -w
