name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build interpret example
      uses: crazy-max/ghaction-xgo@v1.1.0
      with:
          xgo_version: latest
          go_version: 1.14.x
          dest: build/interpret
          pkg: ./cmd/interpret/
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          ldflags: -s -w
      
    - name: Build handles example
      uses: crazy-max/ghaction-xgo@v1.1.0
      with:
          xgo_version: latest
          go_version: 1.14.x
          dest: build/handles
          pkg: ./cmd/handles/
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          ldflags: -s -w
          
    - name: Upload interpret artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          # Artifact name
          name: interpret
          # Directory containing files to upload
          path: build/interpret
      
    - name: Upload handles artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          # Artifact name
          name: handles
          # Directory containing files to upload
          path: build/handles
